### ISSUE TITLE
Possible bug on reduce storage

### ISSUE THREAD

**Issue by robbestad** [GenesysGo/shadow-drive-cli#9]
I was able to reduce storage on a drive to less than current usage. Bug?

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1560743/192120240-f470e986-3c02-4f07-ba41-fe421dd5feed.png">

**Comment by tracy-codes** [comment]
What steps did you take to produce this?

For example, did you reduce storage and upload a file simultaneously or within a short period close to each other?

**Comment by robbestad** [comment]
I simply reduced storage on an existing drive that I last uploaded to about a day ago. I can also reproduce this on another drive-- in fact I did, and then added storage to get it on the plus side. I used the resize button in that screenshot, but it simply calls the SDK so it should be reproducable with the CLI too.

**Comment by tracy-codes** [comment]
@robbestad This bug is now be resolved.
